Большие изменения в DDD моделях
week-password/wlss-wiki pull request #3
Opened 2023-07-21 14:12 UTC by birthdaysgift

- переименована сущность Пользователь -> Аккаунт
- статья "Модель. Дружба" дополнена ограничениями

2023-07-23 22:31 UTC, birthdaysgift commented on wiki/wlss/model__wish.md
> +Обязательный атрибут **Профиля**, используется для хранения ссылки на **Аккаунт** пользователя создавшего желание (владеющего желанием).
Заменить "Профиля" -> "Желания"

2023-07-23 22:33 UTC, birthdaysgift commented on wiki/wlss/model__wish.md
>  Представляет из себя строку от 1 до 10000 символов (включительно). Может содержать любые символы. Не может содержать больше двух пробелов идущих подряд, а также начинаться и заканчиваться пробелом.
кажется мы где то решали, что ограничение на пробелы излишне. Напрямую к мр-у не относится, но заодно тоже можно поправить

И желательно найти обсуждение в котором это решалось

2023-07-24 10:36 UTC, birthdaysgift commented on wiki/wlss/model__wish.md
>  Представляет из себя строку от 1 до 10000 символов (включительно). Может содержать любые символы. Не может содержать больше двух пробелов идущих подряд, а также начинаться и заканчиваться пробелом.
> И желательно найти обсуждение в котором это решалось

https://github.com/week-password/wisher/discussions/7?sort=new#discussioncomment-5937171

2023-07-24 15:11 UTC, fowesn requested changes

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__account.md
> +Представляет из себя строку длиной от 8 до 500 символов (включительно). Допустимые символы - `А-Я`, `а-я`, ASCII (с 33 по 126 включительно).
До переименования модели Пользователя в модель Аккаунта приняли решение, что допустимые символы пароля - любые, так что тут это нужно поправить

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__account.md
> +Объект, являющийся обязательным атрибутом сущности **Аккаунта**.
Можно для консистентности написать "Обязательный атрибут Аккаунта пользователя", как у атрибутов Логин и Почта

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__friendship.md
> +Объект определяющий отношения "Дружбы" между пользователями А и Б. Содержит ссылки на **Аккаунты** этих пользователей.
```suggestion
Объект, определяющий отношения "Дружбы" между пользователями А и Б. Содержит ссылки на **Аккаунты** этих пользователей.
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__friendship.md
> +Список **Друзей** связанных с **Аккаунтом** пользователя виден всем другим **Аккаунтам** пользователей системы.
```suggestion
Список **Друзей**, связанных с **Аккаунтом** пользователя, виден всем другим **Аккаунтам** пользователей системы.
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__friendship.md
> +Объекты **Дружбы** связывающие **Аккаунты** пользователей А и Б могут быть созданы, только если существует одна и только одна одобренная **Заявка в друзья**, ссылающаяся **Аккаунты** этих пользовател
```suggestion
Объекты **Дружбы**, связывающие **Аккаунты** пользователей А и Б, могут быть созданы, только если существует одна и только одна одобренная **Заявка в друзья**, ссылающаяся на **Аккаунты** этих пользователей.
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__friendship.md
> +Обязательный атрибут объекта **Дружба**. Хранит ссылку на **Аккаунт** пользователя у которого есть **Друг**.
```suggestion
Обязательный атрибут объекта **Дружба**. Хранит ссылку на **Аккаунт** пользователя, у которого есть **Друг**.
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__friendship.md
> +Таким образом, **Другом** пользователя А является пользователь Б, если существует объект **Дружба**, в котором атрибут **Аккаунт** указывает на **Аккаунт** пользователя А, и атрибут **Друг** указывае
```suggestion
Таким образом, **Другом** пользователя А является пользователь Б, если существует объект **Дружба**, в котором атрибут **Аккаунт** указывает на **Аккаунт** пользователя А и атрибут **Друг** указывает на **Аккаунт** пользователя Б.
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__friendship.md
> +Дружба может быть только обоюдная, это значит что если существует объект **Дружба**(Аккаунт: А, Друг: Б), то обязательно должен существовать объект **Дружба**(Аккаунт: Б, Друг: А).
```suggestion
Дружба может быть только обоюдная, это значит, что если существует объект **Дружба**(Аккаунт: А, Друг: Б), то обязательно должен существовать объект **Дружба**(Аккаунт: Б, Друг: А).
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__friendship.md
> +Объект представляющий собой заявку в друзья от **Аккаунта** пользователя А к **Аккаунту** пользователя Б. Существование этого объекта обозначает желание пользователя А добавить в друзья пользователя
```suggestion
Объект, представляющий собой заявку в друзья от **Аккаунта** пользователя А к **Аккаунту** пользователя Б. Существование этого объекта обозначает желание пользователя А добавить в друзья пользователя Б.
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__friendship.md
> +Обязательный атрибут объекта **Заявка в друзья**. Хранит ссылку на **Аккаунт** пользователя отправившего (создавшего) заявку.
```suggestion
Обязательный атрибут объекта **Заявка в друзья**. Хранит ссылку на **Аккаунт** пользователя, отправившего (создавшего) заявку.
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__friendship.md
> +- существует неотклонённая **Заявка в друзья** связывающая **Аккаунты** пользователей А и Б
```suggestion
- существует неотклонённая **Заявка в друзья**, связывающая **Аккаунты** пользователей А и Б
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__friendship.md
> +- существует хотя бы один объект **Дружба** связывающий **Аккаунты** пользователей А и Б
```suggestion
- существует хотя бы один объект **Дружба**, связывающий **Аккаунты** пользователей А и Б
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__friendship.md
> +**Заявка в друзья** не может указывать на два одинаковых **Аккаунта** (иными словами пользователь не может создать **Заявку в друзья** к самому себе).
```suggestion
**Заявка в друзья** не может указывать на два одинаковых **Аккаунта** (иными словами, пользователь не может создать **Заявку в друзья** к самому себе).
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__friendship.md
> +Существовние более чем одной **Заявки в друзья** связывающей **Аккаунты** пользователей А и Б невозможно. Если существует отклонённая **Заявка в друзья** связывающая Аккаунты пользователей А и Б, то
```suggestion
Существование более чем одной **Заявки в друзья**, связывающей **Аккаунты** пользователей А и Б, невозможно. Если существует отклонённая **Заявка в друзья**, связывающая Аккаунты пользователей А и Б, то при создании новой **Заявки** старая (отклонённая) удаляется.
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__friendship.md
> +Если **Заявка в друзья** связывающая **Аккаунты** пользователей А и Б, находится в статусе **"Одобрена"** (Accepted), то должны существовать два объекта **Дружбы** - **Дружба**(Аккаунт: А, Друг: Б) и
```suggestion
Если **Заявка в друзья**, связывающая **Аккаунты** пользователей А и Б, находится в статусе **"Одобрена"** (Accepted), то должны существовать два объекта **Дружбы** - **Дружба**(Аккаунт: А, Друг: Б) и **Дружба**(Аккаунт: Б, Друг: А).
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__account.md
> +_Также может употребляться как "Аккаунт пользователя" в определённых контекстах, где нужна более литературная формулировка. При этом смысл определения "Аккаунт пользователя" тот же что и у определени
```suggestion
_Также может употребляться как "Аккаунт пользователя" в определённых контекстах, где нужна более литературная формулировка. При этом смысл определения "Аккаунт пользователя" тот же, что и у определения "Аккаунт"._
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__account.md
> +Не виден пользователям других **Аккаунтов** внутри системы, используется только для аутентификации и формирования url-ссылки на веб страницы связанные с пользователем этого **Аккаунта**.
```suggestion
Не виден пользователям других **Аккаунтов** внутри системы, используется только для аутентификации и формирования url-ссылки на веб-страницы, связанные с пользователем этого **Аккаунта**.
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__account.md
> +Используется для хранения алгоритма, с помощью которого был сгенерирован хэш. Это необходимо чтобы в дальнейшем можно было сгенерировать такой же хэш.
```suggestion
Используется для хранения алгоритма, с помощью которого был сгенерирован хэш. Это необходимо, чтобы в дальнейшем можно было сгенерировать такой же хэш.
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__account.md
> +Представляет из себя строку из множества строк являющихся результатом работы алгоритма хэширования.
```suggestion
Представляет из себя строку из множества строк, являющихся результатом работы алгоритма хэширования.
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__wish.md
> +Желания связанные с **Аккаунтом** пользователя А видят только пользователи, **Аккаунты** которых связаны с **Аккаунтом** пользователя А отношениями **Дружбы**.
```suggestion
Желания, связанные с **Аккаунтом** пользователя А, видят только пользователи, **Аккаунты** которых связаны с **Аккаунтом** пользователя А отношениями **Дружбы**.
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__wish.md
> +Обязательный атрибут **Профиля**, используется для хранения ссылки на **Аккаунт** пользователя создавшего желание (владеющего желанием).
```suggestion
Обязательный атрибут **Желания**, используется для хранения ссылки на **Аккаунт** пользователя, создавшего желание (владеющего желанием).
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__wish.md
>  Представляет из себя строку от 1 до 10000 символов (включительно). Может содержать любые символы. Не может содержать больше двух пробелов идущих подряд, а также начинаться и заканчиваться пробелом.
это ограничение можно соблюсти только на фронте, но не делать его частью модели

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__wish.md
> +Таким образом **Желание** А, считается забронированным пользователем **Аккаунта** Б, если существует **Бронь желания**(Желание: А, Аккаунт: Б).
```suggestion
Таким образом, **Желание** А считается забронированным пользователем **Аккаунта** Б, если существует **Бронь желания**(Желание: А, Аккаунт: Б).
```

2023-07-24 15:11 UTC, fowesn commented on wiki/wlss/model__wish.md
> +**Бронь Желания**, ссылающаяся на **Желание** А, может существовать только если не существует другой **Брони Желания**, ссылающейся на **Желание** А.
```suggestion
**Бронь Желания**, ссылающаяся на **Желание** А, может существовать, только если не существует другой **Брони Желания**, ссылающейся на **Желание** А.
```

2023-07-26 12:07 UTC, merged